In [3]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [4]:
# Podemos crear array de una dimension con la función np.array()
array_unidim = np.array([1, 2, 3, 4, 5])

# Un array de dos dimensiones
array_bidim = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Un array de tres dimensiones
array_tridim = np.array([[[1, 2, 3],
                          [4, 5, 6]],
                          [[7, 8, 9],
                           [10, 11, 12]]])

In [5]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño y tipo)
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [6]:
# Atributos del array bidimensional
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [7]:
# Atributos del array tridimensional
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [8]:
# Importamos pandas con pd y creamos ua DataFrame a partir de array bidimensional
import pandas as pd

datos = pd.DataFrame(array_bidim)
datos

,0,1,2
0,1,2,3
1,4,5,6


In [9]:
# Creamos un array de tamaño 4x3, fomrado únicamente de unos (1)
unos = np.ones((4, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Creamos un array de tamaño 2x3x2, formado únicamente por ceros (0)
cero = np.zeros((2, 4, 3))
cero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 101, 5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [12]:
# Creammos un array de números aleatorios enteros comprendidos netre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0, 10, (2, 5))
array_2

array([[7, 8, 5, 3, 4],
       [4, 4, 8, 9, 6]])

In [13]:
# Creamos un array de números aleatorios decimales comprendidos entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3, 5))
array_3

array([[0.42487102, 0.4180938 , 0.23118895, 0.51183924, 0.62892996],
       [0.79616805, 0.97324315, 0.25491106, 0.25511326, 0.53893339],
       [0.6748643 , 0.17264342, 0.66181626, 0.55982288, 0.79885993]])

In [14]:
# Establece la "semilla" de números aleatorios en 27
np.random.seed(27)

In [15]:
# Creamos un array de números leatorios enteros comprendidos entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0, 10, (3, 5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

In [16]:
# Encontramos los valores únicos del array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [17]:
# Extraemos el elemento del índice 1 del array 4
array_4[1]

array([5, 8, 9, 1, 2])

In [18]:
# Extraemos las primeras dos filas de array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [19]:
# Extraemos los dos primeos datos de las primeras dos filas del array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [20]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3, 4))

In [21]:
# Invocamos al array_5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [22]:
# Invocamos al array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# Sumamos los dos arrays
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [24]:
# Creamos un array de tamaño (4, 3)lleno de unos
array_7 = np.ones((4, 3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# Intentemos sumar los arrays 6 y 7
array_6 + array_7

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 